full_rebuild: true
title: "Windows 2008/R2 Migration Notebook"
name: "Windows 2008/R2 Migration Notebook"
author: "Microsoft Corporation"
tracking: win2kmigrate
email: swilder@microsoft.com
description: >- # this means to ignore newlines until "baseurl:"
  This notebook provides useful information for discussing Windows Server 2008/R2 
  migrations to Microsoft Azure public cloud.
baseurl: "/www" # the subpath of your site, e.g. /blog
url: "http://swilder0123.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    values:
      layout: "index"
markdown: kramdown
kramdown:
  input: GFM
relative_permalinks: false
collections:
- entries
sass:
  sass_dir: _sass
  style: :compressed
exclude: [
.git,
.gitignore,
README.md,
.sass-cache
]
